# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

try:
    from atred.proto import transmitter_pb2 as transmitter__pb2
except:
    pass

try:
    import transmitter_pb2 as transmitter__pb2
except:
    pass


class TransmitterStub(object):
    """A simple key-value storage service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Transmit = channel.unary_unary(
                '/transmitter.Transmitter/Transmit',
                request_serializer=transmitter__pb2.Request.SerializeToString,
                response_deserializer=transmitter__pb2.Response.FromString,
                )


class TransmitterServicer(object):
    """A simple key-value storage service
    """

    def Transmit(self, request, context):
        """Provides a value for each key request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransmitterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Transmit': grpc.unary_unary_rpc_method_handler(
                    servicer.Transmit,
                    request_deserializer=transmitter__pb2.Request.FromString,
                    response_serializer=transmitter__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'transmitter.Transmitter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transmitter(object):
    """A simple key-value storage service
    """

    @staticmethod
    def Transmit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/transmitter.Transmitter/Transmit',
            transmitter__pb2.Request.SerializeToString,
            transmitter__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
